# Generated by Django 2.0.3 on 2018-03-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('APPROVED', 'approved')], default='PENDING', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nominator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('EC', 'Early Career'), ('MS', 'Mid/Senior Career')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=200)),
                ('linkedin_link', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, choices=[('EC', 'Early Career'), ('MS', 'Mid/Senior Career')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='nomination',
            name='nominator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchers.Nominator'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='nominee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researchers.Nominee'),
        ),
    ]
