# Generated by Django 2.0.2 on 2018-03-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='levels',
        ),
        migrations.AddField(
            model_name='researcher',
            name='level',
            field=models.CharField(blank=True, choices=[('EC', 'Early Career'), ('MS', 'Mid/Senior Career')], max_length=1),
        ),
    ]
