# Generated by Django 2.0.3 on 2018-03-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='nominator',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='nominee',
        ),
        migrations.DeleteModel(
            name='Nomination',
        ),
        migrations.DeleteModel(
            name='Nominator',
        ),
        migrations.DeleteModel(
            name='Nominee',
        ),
    ]
