# Generated by Django 2.0.3 on 2018-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_auto_20180331_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='des',
            field=models.CharField(default='hellodefault', max_length=200),
            preserve_default=False,
        ),
    ]
