# Generated by Django 2.0.3 on 2018-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0003_researcher_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='email',
            field=models.CharField(default=999, max_length=200),
            preserve_default=False,
        ),
    ]
