# Generated by Django 2.0.3 on 2018-05-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0004_researcher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='level',
            field=models.CharField(blank=True, choices=[('AP', 'Assistant Professor'), ('AsCP', 'Associate Professor'), ('FP', 'Full Professor'), ('SIS', 'Senior Industry Scientist')], max_length=200),
        ),
    ]
