# Generated by Django 2.0.3 on 2018-05-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0005_auto_20180510_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='level',
            field=models.CharField(blank=True, choices=[('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Full Professor', 'Full Professor'), ('Senior Industry Scientist', 'Senior Industry Scientist')], max_length=200),
        ),
    ]
