# Generated by Django 2.0.4 on 2019-03-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0006_auto_20180515_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='researcher',
            name='lastname',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
