# Generated by Django 2.0.4 on 2019-03-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0007_auto_20190312_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='fullname',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
