# Generated by Django 2.0.4 on 2019-03-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0008_researcher_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='linkedin_link',
        ),
    ]
