#!/bin/bash -e
. ~/researcher-app-stretch/venv/bin/activate
cd "$(dirname "$0")"
PYTHONPATH=~/researcher-app-stretch/src:$PYTHONPATH \
    exec gunicorn -w 2 -b unix:/srv/apps/$(whoami)/$(whoami).sock \
    --log-file - dbapp.wsgi:application
